deploy:
  script: echo Deploy!
  environment:
    name: prod-$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.dev.company.com
    on_stop: stop_job

stop_job:
  script: echo Stop!
  when: manual
  environment:
    name: prod-$CI_COMMIT_REF_SLUG
    action: stop
