# .gitlab-ci.yml

image: golang

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build -o hello-linux main.go
    - GOOS=darwin GOARCH=arm64 go build -o hello-mac main.go
  artifacts:
    paths:
      - hello-linux
      - hello-mac

test:
  stage: test
  script:
    - ./hello-linux
