# .gitlab-ci.yml

image: golang

stages:
  - build

.job: &job
  stage: build
  only:
    - main

build:
  <<: *job
  parallel: &matrix
    matrix:
      - GOOS: linux
        GOARCH:
          - amd64
          - arm64
      - GOOS: darwin
        GOARCH:
          - amd64
          - arm64
      - GOOS: windows
        GOARCH:
          - amd64
  script: go build -o hello-$GOOS-$GOARCH main.go
  artifacts:
    paths:
        - hello-*

build2:
  <<: *job
  parallel:
    <<: *matrix
  script: go build -o hello2-$GOOS-$GOARCH main.go
