image: sikalabs/ci

variables:
  HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN

deploy:
  script:
    - env | grep KUBE
    - helm repo add sikalabs https://helm.sikalabs.io
    - helm upgrade --install $CI_PROJECT_PATH_SLUG -n default sikalabs/hello-world --set host=$HOST
  environment:
    name: prod-$CI_COMMIT_REF_SLUG
    url: https://$HOST
