# .gitlab-ci.yml

image: golang

stages:
  - build

.parallel:
  parallel:
    matrix:
      - GOOS: linux
        GOARCH:
          - amd64
          - arm64
      - GOOS: darwin
        GOARCH:
          - amd64
          - arm64
      - GOOS: windows
        GOARCH:
          - amd64

.job:
  stage: build

build:
  extends:
    - .job
    - .parallel
  script: go build -o hello-$GOOS-$GOARCH main.go
  artifacts:
    paths:
        - hello-*

build2:
  extends:
    - .job
    - .parallel
  script: go build -o hello2-$GOOS-$GOARCH main.go
