# .gitlab-ci.yml

demo:
  trigger: example/martinkonecny

foo:
  variables:
    PREFIX: foo
  trigger:
    include: https://gitlab.sikademo.com/example/ci/-/raw/main/simple-k8s.yml
    strategy: depend

bar:
  variables:
    PREFIX: bar
  trigger:
    include: https://gitlab.sikademo.com/example/ci/-/raw/main/simple-k8s.yml
    strategy: depend
