# .gitlab-ci.yml

stages:
  - deploy
  - deploy_verification

deploy:
  stage: deploy
  when: manual
  script: echo test ...


deploy_verification:
  stage: deploy_verification
  script: echo test ...false
