# .gitlab-ci.yml

image: golang

stages:
  - build

build:
  stage: build
  parallel:
    matrix:
      - GOOS: linux
        GOARCH:
          - amd64
          - arm64
      - GOOS: darwin
        GOARCH:
          - amd64
          - arm64
      - GOOS: windows
        GOARCH:
          - amd64
  script: go build -o hello-$GOOS-$GOARCH main.go
  artifacts:
    paths:
        - hello-*
